red:
  puerto: 27015
  ip: "127.0.0.1"
  ID: 1
  alias: "Juana de Arco"
pantalla: 
  ancho: 640
  alto: 480
  fullscreen: 0 # 1 = true, 0 = false
gameplay: 
  scroll_margen: 60
  scroll_vel: 20
log:
  warnings: 1
  info: 0
  errors: 1
tipo:
  - nombre: "moneda"
    ruta: "coin.png"
    subX: 10
    pixelX: 10
    pixelY: 10
    fps: 10
    score: 1
  - nombre: "champion"
    ruta: "championAOE.png"
    subX: 10
    subY: 8
    pixelX: 21
    pixelY: 38
    fps: 10
    delay: 15
  - nombre: "champion_move"
    ruta: "champion_moveAOE.png"
    subX: 10
    subY: 8
    pixelX: 21
    pixelY: 38
    delay: 0
    fps: 20
  - nombre: "castle"
    ruta: "castleAOE.png"
    pixelX: 148
    pixelY: 177
  - nombre: "knight"
    ruta: "knightAOE.png"
    subX: 10
    subY: 8
    pixelX: 34
    pixelY: 41
    fps: 8
    delay: 3
  - nombre: "knight_move"
    ruta: "knight_moveAOE.png"
    subX: 10
    subY: 8
    pixelX: 26
    pixelY: 49
    fps: 18
    delay: 0
  - nombre: "house"
    ruta: "houseAOE.png"
    sizeX: 3
    sizeY: 3
    pixelX: 76
    pixelY: 42
  - nombre: "tile"
    ruta: "tileG.png"
    pixelX: 26
    pixelY: 0
  - nombre: "tileHuge"
    ruta: "tileHuge.png"
    tipo: "none"
    pixelX: 260
    pixelY: 0
  - nombre: "windmill"
    ruta: "windmillAOE.png"
    subX: 8
    subY: 1
    pixelX: 84
    pixelY: 53
    fps: 10
    delay: 0
  - nombre: "town_center"
    ruta: "townCenterAOE.png"
    pixelX: 56
    pixelY: 159
  - nombre: "barracks"
    ruta: "barracksAOE.png"
    pixelX: 101
    pixelY: 41
  - nombre: "archery"
    ruta: "archeryAOE.png"
    pixelX: 101
    pixelY: 47
  - nombre: "stable"
    ruta: "stableAOE.png"
    pixelX: 101
    pixelY: 12