red:
  puerto: 27015
  ip: "127.0.0.1"
  ID: 1
  alias: "Juana de Arco"
pantalla: 
  ancho: 640
  alto: 480
  fullscreen: 0 # 1 = true, 0 = false
gameplay: 
  scroll_margen: 60
  scroll_vel: 20
log:
  warnings: 1
  info: 0
  errors: 1
tipo:
  - nombre: "moneda"
    ruta: "coin.png"
    subX: 10
    pixelX: 10
    pixelY: 10
    fps: 10
    score: 1
  - nombre: "screen_frame"
    ruta: "screenFrame.png"
  - nombre: "font"
    ruta: "font.png"
  - nombre: "champion_icon"
    ruta: "champion_icon.png"
  - nombre: "knight_icon"
    ruta: "knight_icon.png"
  - nombre: "pikeman_icon"
    ruta: "pikeman_icon.png"
  - nombre: "ram_icon"
    ruta: "ram_icon.png"
  - nombre: "castle_icon"
    ruta: "castle_icon.png"
  - nombre: "archery_icon"
    ruta: "archery_icon.png"
  - nombre: "barracks_icon"
    ruta: "barracks_icon.png"
  - nombre: "stable_icon"
    ruta: "stable_icon.png"
  - nombre: "windmill_icon"
    ruta: "windmill_icon.png"
  - nombre: "house_icon"
    ruta: "house_icon.png"
  - nombre: "attack_icon"
    ruta: "attack_icon.png"
  - nombre: "range_icon"
    ruta: "range_icon.png"
  - nombre: "armor_icon"
    ruta: "armor_icon.png"
  - nombre: "champion"
    ruta: "championAOE.png"
    subX: 10
    subY: 8
    pixelX: 21
    pixelY: 38
    fps: 10
    delay: 15
  - nombre: "champion_move"
    ruta: "champion_moveAOE.png"
    subX: 10
    subY: 8
    pixelX: 21
    pixelY: 38
    delay: 0
    fps: 20
  - nombre: "castle"
    ruta: "castleAOE.png"
    pixelX: 148
    pixelY: 177
  - nombre: "knight"
    ruta: "knightAOE.png"
    subX: 10
    subY: 8
    pixelX: 22
    pixelY: 41
    fps: 8
    delay: 3
  - nombre: "knight_move"
    ruta: "knight_moveAOE.png"
    subX: 10
    subY: 8
    pixelX: 29
    pixelY: 52
    fps: 18
    delay: 0
  - nombre: "house"
    ruta: "houseAOE.png"
    pixelX: 76
    pixelY: 42
  - nombre: "tile"
    ruta: "tileG.png"
    pixelX: 26
    pixelY: 0
  - nombre: "tileSlct"
    ruta: "tileSelec.png"
    pixelX: 26
    pixelY: 0
  - nombre: "tileHuge"
    ruta: "tileHuge.png"
    tipo: "none"
    pixelX: 260
    pixelY: 0
  - nombre: "windmill"
    ruta: "windmillAOE.png"
    subX: 8
    subY: 1
    pixelX: 84
    pixelY: 57
    fps: 10
    delay: 0
  - nombre: "town_center"
    ruta: "townCenterAOE.png"
    pixelX: 56
    pixelY: 159
  - nombre: "barracks"
    ruta: "barracksAOE.png"
    pixelX: 101
    pixelY: 53
  - nombre: "archery"
    ruta: "archeryAOE.png"
    pixelX: 103
    pixelY: 49
  - nombre: "stable"
    ruta: "stableAOE.png"
    pixelX: 102
    pixelY: 15
  - nombre: "champion2"
    ruta: "championAOEp2.png"
    subX: 10
    subY: 8
    pixelX: 21
    pixelY: 38
    fps: 10
    delay: 15
  - nombre: "champion_move2"
    ruta: "champion_moveAOEp2.png"
    subX: 10
    subY: 8
    pixelX: 21
    pixelY: 38
    delay: 0
    fps: 20
  - nombre: "castle2"
    ruta: "castleAOEp2.png"
    pixelX: 148
    pixelY: 177
  - nombre: "knight2"
    ruta: "knightAOEp2.png"
    subX: 10
    subY: 8
    pixelX: 34
    pixelY: 41
    fps: 8
    delay: 3
  - nombre: "knight_move2"
    ruta: "knight_moveAOEp2.png"
    subX: 10
    subY: 8
    pixelX: 26
    pixelY: 49
    fps: 18
    delay: 0
  - nombre: "house2"
    ruta: "houseAOEp2.png"
    pixelX: 76
    pixelY: 42
  - nombre: "windmill2"
    ruta: "windmillAOEp2.png"
    subX: 8
    subY: 1
    pixelX: 84
    pixelY: 57
    fps: 10
    delay: 0
  - nombre: "town_center2"
    ruta: "townCenterAOEp2.png"
    pixelX: 56
    pixelY: 159
  - nombre: "barracks2"
    ruta: "barracksAOEp2.png"
    pixelX: 101
    pixelY: 53
  - nombre: "archery2"
    ruta: "archeryAOEp2.png"
    pixelX: 103
    pixelY: 49
  - nombre: "stable2"
    ruta: "stableAOEp2.png"
    pixelX: 102
    pixelY: 15
  - nombre: "champion3"
    ruta: "championAOEp3.png"
    subX: 10
    subY: 8
    pixelX: 21
    pixelY: 38
    fps: 10
    delay: 15
  - nombre: "champion_move3"
    ruta: "champion_moveAOEp3.png"
    subX: 10
    subY: 8
    pixelX: 21
    pixelY: 38
    delay: 0
    fps: 20
  - nombre: "castle3"
    ruta: "castleAOEp3.png"
    pixelX: 148
    pixelY: 177
  - nombre: "knight3"
    ruta: "knightAOEp3.png"
    subX: 10
    subY: 8
    pixelX: 34
    pixelY: 41
    fps: 8
    delay: 3
  - nombre: "knight_move3"
    ruta: "knight_moveAOEp3.png"
    subX: 10
    subY: 8
    pixelX: 26
    pixelY: 49
    fps: 18
    delay: 0
  - nombre: "house3"
    ruta: "houseAOEp3.png"
    pixelX: 76
    pixelY: 42
  - nombre: "windmill3"
    ruta: "windmillAOEp3.png"
    subX: 8
    subY: 1
    pixelX: 84
    pixelY: 57
    fps: 10
    delay: 0
  - nombre: "town_center3"
    ruta: "townCenterAOEp3.png"
    pixelX: 56
    pixelY: 159
  - nombre: "barracks3"
    ruta: "barracksAOEp3.png"
    pixelX: 101
    pixelY: 53
  - nombre: "archery3"
    ruta: "archeryAOEp3.png"
    pixelX: 103
    pixelY: 49
  - nombre: "stable3"
    ruta: "stableAOEp3.png"
    pixelX: 102
    pixelY: 15
  - nombre: "Gchampion"
    ruta: "GchampionAOE.png"
    subX: 10
    subY: 8
    pixelX: 21
    pixelY: 38
    fps: 10
    delay: 15
  - nombre: "Gchampion_move"
    ruta: "Gchampion_moveAO.png"
    subX: 10
    subY: 8
    pixelX: 21
    pixelY: 38
    delay: 0
    fps: 20
  - nombre: "Gcastle"
    ruta: "GcastleAOE.png"
    pixelX: 148
    pixelY: 177
  - nombre: "Gknight"
    ruta: "GknightAOE.png"
    subX: 10
    subY: 8
    pixelX: 34
    pixelY: 41
    fps: 8
    delay: 3
  - nombre: "Gknight_move"
    ruta: "Gknight_moveAOE.png"
    subX: 10
    subY: 8
    pixelX: 26
    pixelY: 49
    fps: 18
    delay: 0
  - nombre: "Ghouse"
    ruta: "GhouseAOE.png"
    pixelX: 76
    pixelY: 42
  - nombre: "Gwindmill"
    ruta: "GwindmillAOE.png"
    subX: 8
    subY: 1
    pixelX: 84
    pixelY: 57
    fps: 10
    delay: 0
  - nombre: "Gtown_center"
    ruta: "GtownCenterAOE.png"
    pixelX: 56
    pixelY: 159
  - nombre: "Gbarracks"
    ruta: "GbarracksAOE.png"
    pixelX: 101
    pixelY: 53
  - nombre: "Garchery"
    ruta: "GarcheryAOE.png"
    pixelX: 103
    pixelY: 49
  - nombre: "Gstable"
    ruta: "GstableAOE.png"
    pixelX: 102
    pixelY: 15
  - nombre: "ram"
    ruta: "ramAOE.png"
    pixelX: 36
    pixelY: 47
    subX: 1
    subY: 8
  - nombre: "ram2"
    ruta: "ramAOEp2.png"
    pixelX: 36
    pixelY: 47
    subX: 1
    subY: 8
  - nombre: "ram3"
    ruta: "ramAOEp3.png"
    pixelX: 36
    pixelY: 47
    subX: 1
    subY: 8
  - nombre: "Gram"
    ruta: "GramAOE.png"
    pixelX: 36
    pixelY: 47
    subX: 1
    subY: 8
  - nombre: "ram_move"
    ruta: "ram_moveAOE.png"
    pixelX: 36
    pixelY: 51
    subX: 15
    subY: 8
    fps: 6
  - nombre: "ram_move2"
    ruta: "ram_moveAOEp2.png"
    pixelX: 36
    pixelY: 51
    subX: 15
    subY: 8
    fps: 6
  - nombre: "ram_move3"
    ruta: "ram_moveAOEp3.png"
    pixelX: 36
    pixelY: 51
    subX: 15
    subY: 8
    fps: 6
  - nombre: "Gram_move"
    ruta: "Gram_moveAOE.png"
    pixelX: 36
    pixelY: 51
    subX: 15
    subY: 8
    fps: 6
  - nombre: "pikeman"
    ruta: "pikemanAOE.png"
    pixelX: 30
    pixelY: 42
    subX: 8
    subY: 8
    fps: 7
    delay: 11
  - nombre: "pikeman2"
    ruta: "pikemanAOEp2.png"
    pixelX: 30
    pixelY: 42
    subX: 8
    subY: 8
    fps: 7
    delay: 11
  - nombre: "pikeman3"
    ruta: "pikemanAOEp3.png"
    pixelX: 30
    pixelY: 42
    subX: 8
    subY: 8
    fps: 7
    delay: 11
  - nombre: "Gpikeman"
    ruta: "GpikemanAOE.png"
    pixelX: 30
    pixelY: 42
    subX: 8
    subY: 8
    fps: 7
    delay: 11
  - nombre: "pikeman_move"
    ruta: "pikeman_moveAOE.png"
    pixelX: 24
    pixelY: 41
    subX: 10
    subY: 8
    fps: 7
  - nombre: "pikeman_move2"
    ruta: "pikeman_moveAOEp2.png"
    pixelX: 24
    pixelY: 41
    subX: 10
    subY: 8
    fps: 7
  - nombre: "pikeman_move3"
    ruta: "pikeman_moveAOEp3.png"
    pixelX: 24
    pixelY: 41
    subX: 10
    subY: 8
    fps: 7
  - nombre: "Gpikeman_move"
    ruta: "Gpikeman_moveAOE.png"
    pixelX: 24
    pixelY: 41
    subX: 10
    subY: 8
    fps: 7