log:
  warnings: 1
  info: 0
  errors: 1
jugadores:
  - nombre: "Juana de Arco"
    id: 1
    color: "azul"
  - nombre: "Genghis Khan"
    id: 2
    color: "rojo"
  - nombre: "Saladino"
    id: 3
    color: "amarillo"
entidades:
  - nombre: "moneda"
    tipo: "resource"
    score: 1
  - nombre: "champion"
    tipo: "unit"
    velocidad: 10
    vision: 4
  - nombre: "castle"
    tipo: "building"
    sizeX: 6
    sizeY: 6
  - nombre: "knight"
    tipo: "unit"
    velocidad: 20
    vision: 5
  - nombre: "house"
    tipo: "building"
    sizeX: 3
    sizeY: 3
  - nombre: "windmill"
    tipo: "building"
    sizeX: 3
    sizeY: 3
  - nombre: "town_center"
    tipo: "building"
    sizeX: 2
    sizeY: 2
  - nombre: "barracks"
    tipo: "building"
    sizeX: 4
    sizeY: 4
  - nombre: "archery"
    tipo: "building"
    sizeX: 4
    sizeY: 4
  - nombre: "stable"
    tipo: "building"
    sizeX: 4
    sizeY: 4
escenario:
  nombre: DEFAULT_MAP
  sizeX: 40
  sizeY: 40
  entidades:
   - {x: 4, y: 12, tipo: "house", p: 1}
   - {x: 4, y: 3, tipo: "windmill", p: 1}
   - {x: 1, y: 6, tipo: "castle", p: 2}
   - {x: 1, y: 12, tipo: "house", p: 3}
   - {x: 18, y: 25, tipo: "house", p: 2}
   - {x: 18, y: 21, tipo: "house", p: 3}
   - {x: 5, y: 23, tipo: "windmill", p: 2}
   - {x: 5, y: 31, tipo: "windmill", p: 1}
   - {x: 13, y: 9, tipo: "castle", p: 2}
   - {x: 10, y: 11, tipo: "house", p: 3}
   - {x: 16, y: 6, tipo: "house", p: 3}
   - {x: 35, y: 35, tipo: "moneda"}
   - {x: 36, y: 35, tipo: "moneda", p: 0}
   - {x: 25, y: 25, tipo: "stable", p: 2}
   - {x: 5, y: 0, tipo: "windmill", p: 1}
   - {x: 22, y: 15, tipo: "barracks", p: 2}
   - {x: 23, y: 21, tipo: "archery", p: 2}
   - {x: 5, y: 18, tipo: "barracks", p: 3}
   - {x: 9, y: 18, tipo: "barracks", p: 1}
   - {x: 32, y: 36, tipo: "champion", p: 2}
   - {x: 37, y: 34, tipo: "knight", p: 1}
   - {x: 37, y: 30, tipo: "champion", p: 3}